### ISSUE TITLE
Material Design Compliance

### ISSUE THREAD

**Issue by KuzonFyre** [KyleMcMullin/CS3450-Group7#44]
Jetpack Compose Library integrated with Material Design 3. 
https://developer.android.com/jetpack/androidx/releases/compose-material3

**Comment by KuzonFyre** [comment]
### Dependency 
#43

**Comment by KyleMcMullin** [comment]
@all We will need to make sure that all components fall under this basis. We should not hardcode any specific colors into our composables. If we only use material design color and design features then it will make it a lot easier down the road to change the colors of all componenents. [Link discussing jetpack compose themes and colors for material design](https://developer.android.com/jetpack/compose/themes/material) This link should have the majority of the documentation needed, including colors, theme colors, surfaces, overlays, text styles, etc.

**Comment by KuzonFyre** [comment]
No longer going to support this.
