### ISSUE TITLE
Material Design color basis

### ISSUE THREAD

**Issue by KyleMcMullin** [KyleMcMullin/CS3450-Group7#45]
Parent #50
We need to define a color basis for material design since all our components will use the basic configs we setup for material design

**Comment by KuzonFyre** [comment]
Completed and awaiting Pull request #59

**Comment by KyleMcMullin** [comment]
https://user-images.githubusercontent.com/85273726/191602909-333c0f0f-c618-42bd-9bc6-09bf7e532643.png
Changes do not compile in android studio, reverting merge commit

**Comment by KuzonFyre** [comment]
Library not available. Delaying finish until I can figure this out.

**Comment by KuzonFyre** [comment]
Solved this on another issue.
