### ISSUE TITLE
Add Firebase API token to Environment Variables

### ISSUE THREAD

**Issue by KyleMcMullin** [KyleMcMullin/CS3450-Group7#74]
Currently listed as a public repo, with anybody having access to the Firebase token. Either add this as an environment variable, or add TA/Watson as collaborators?

**Comment by ablibranix** [comment]
Just emailed TA and making project private and adding him as a collaborator. Will update with what he says.

**Comment by ablibranix** [comment]
@KyleMcMullin TA's github - https://github.com/AndrewCurtis27

**Comment by ablibranix** [comment]
Decided it was not needed.
